### PR TITLE
Get nodes from Dashboard

### PR DESCRIPTION
**Pull request by KobbyMmo**
## Description

Convert API calls from v2/nodes to call dashboard which uses v1/nodes.
Reduces calls to API from 3 to 1;
Reduce iteration of Sensor values from 3 to 1

Fixes # (issue)

## Type of change

- [x] improve or enhance existing functionality

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
@KobbyMmo ... I think this repo uses tabs for spacing (8 spaces if I remember), etc. Right now I can't tell what is what, since the whole file is changed instead of specific lines.

**Review by kilemensi — COMMENTED** [review]
Any easy way to test this using api.sensors.africa @KobbyMmo ?

**Comment by KobbyMmo** [comment]
@kilemensi 
spin up the local dashboard, and remove the Cors or change the Cors URL to point to the local map endpoint.
Then you can change the map endpoint to point to the local Dashboard.

for the dashboard switch to feat-v1/nodes branch

**Review by kilemensi — APPROVED** [review]
🚀 @KobbyMmo 

------------------------------

I think lets maintain the back-end structure; we can optimize by doing the pagination in the back-end but lets not change the structure.

**Pull request merged**
